import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {SignJWT,importJWK,exportJWK} from 'jose';
import {createAccessVerifier,createAdminAuthorizer,legacyOfficialLocation} from '../src/admin/auth.mjs';
const keys=JSON.parse(fs.readFileSync('tests/helpers/access-test-keys.json')).keys;
const privateKeys=await Promise.all(keys.map(k=>importJWK(k,'RS256')));
const publicKeys=keys.map((k,i)=>Object.fromEntries(Object.entries({...k,kid:'test-'+i,alg:'RS256',use:'sig'}).filter(([n])=>!['d','p','q','dp','dq','qi'].includes(n))));
const issuer='https://fixture-team.cloudflareaccess.com',audience='a'.repeat(64),hostname='fixture-uat.account.workers.dev';
const db={prepare(){throw Error('Authentication must not read the database');}};
const env={DB:db,ADMIN_ENABLED:'true',ADMIN_WRITES_ENABLED:'true',ADMIN_ENVIRONMENT:'uat',ADMIN_HOSTNAME:hostname,ADMIN_ACCESS_ISSUER:issuer,ADMIN_ACCESS_AUD:audience};
const now=()=>Math.floor(Date.now()/1000);
async function token(overrides={},key=0){return new SignJWT({sub:'human-fixture',email:'admin@example.invalid',type:'app',iss:issuer,aud:audience,iat:now(),nbf:now()-1,exp:now()+300,...overrides}).setProtectedHeader({alg:'RS256',kid:'test-'+key}).sign(privateKeys[key]);}
function harness(){const requests=[];let jwks=[publicKeys[0]],unavailable=false;const verify=createAccessVerifier(async url=>{requests.push(String(url));if(unavailable)throw Error('offline');return Response.json({keys:jwks});},{cooldownDuration:0});return {authorize:createAdminAuthorizer(verify),verify,requests,rotate(){jwks=[publicKeys[1]];},offline(){unavailable=true;}};}
const request=(jwt,method='GET',host=hostname,headers={})=>new Request('https://'+host+'/admin/players',{method,headers:{...(jwt?{'Cf-Access-Jwt-Assertion':jwt}:{}),...headers}});
const denied=error=>error.status===403;
test('signed human token supplies only verified actor; shared request verifies once',async()=>{const h=harness(),r=request(await token(), 'GET',hostname,{'Cf-Access-Authenticated-User-Email':'forged@example.invalid'});const result=await h.authorize(r,false,env);assert.deepEqual(result.actor,{sub:'human-fixture',email:'admin@example.invalid'});assert.equal(result.writes,true);assert.equal(await h.authorize(r,false,env),result);assert.deepEqual(h.requests,[issuer+'/cdn-cgi/access/certs']);});
for(const [name,claims]of Object.entries({expired:{exp:now()-60},future:{nbf:now()+60},futureIssued:{iat:now()+60},issuer:{iss:'https://evil.invalid'},audience:{aud:'b'.repeat(64)},emptySub:{sub:''},missingSub:{sub:undefined},emptyEmail:{email:''},missingEmail:{email:undefined},service:{common_name:'service-token'},serviceType:{type:'service'},missingType:{type:undefined},missingExpiry:{exp:undefined}}))test('reject '+name,async()=>{await assert.rejects(harness().authorize(request(await token(claims)),false,env),denied);});
test('wrong signature, malformed, unsigned and unsupported algorithm rejected',async()=>{const h=harness();const valid=await token();const [a,b]=valid.split('.');const wrong=await new SignJWT({iss:issuer,aud:audience}).setProtectedHeader({alg:'HS256'}).sign(new Uint8Array(32));for(const value of [a+'.'+b+'.AAAA','broken',a+'.'+b+'.',wrong])await assert.rejects(h.authorize(request(value),false,env),denied);});
test('missing JWT and forged email alone rejected before key fetch',async()=>{const h=harness();await assert.rejects(h.authorize(request(null,'GET',hostname,{'Cf-Access-Authenticated-User-Email':'admin@example.invalid'}),false,env),denied);assert.equal(h.requests.length,0);});
test('wrong host/environment and incomplete configuration fail closed',async()=>{const h=harness(),jwt=await token();for(const host of ['localhost','other.account.workers.dev','fixture.pages.dev','production.example.invalid'])await assert.rejects(h.authorize(request(jwt,'GET',host),false,env),denied);for(const patch of [{ADMIN_ENABLED:'false'},{ADMIN_ENABLED:undefined},{ADMIN_ACCESS_AUD:undefined},{ADMIN_ACCESS_ISSUER:'https://evil.invalid'},{ADMIN_ACCESS_ISSUER:issuer+'/extra'},{ADMIN_ENVIRONMENT:'production'},{ADMIN_HOSTNAME:'localhost'}])await assert.rejects(h.authorize(request(jwt),false,{...env,...patch}),denied);assert.equal(h.requests.length,0);});
test('independent read/write flags and methods remain closed',async()=>{const h=harness(),jwt=await token();assert.equal((await h.authorize(request(jwt),false,{...env,ADMIN_WRITES_ENABLED:'false'})).writes,false);await assert.rejects(h.authorize(request(jwt,'POST'),false,{...env,ADMIN_WRITES_ENABLED:'false'}),denied);assert.equal((await h.authorize(request(jwt,'POST'),false,env)).writes,true);for(const method of ['PUT','PATCH','DELETE','OPTIONS'])await assert.rejects(h.authorize(request(jwt,method),false,env),e=>e.status===405);});
test('local synthetic actor requires DEV loopback staging and rejects forwarding',async()=>{const h=harness(),local={cflesportsid_staging:db};const accepted=await h.authorize(new Request('http://localhost:4321/admin'),true,local);assert.deepEqual(accepted.actor,{sub:'local-admin',email:'local-admin@example.invalid'});for(const headers of [{'forwarded':'host=localhost'},{'x-forwarded-for':'1.2.3.4'},{'x-forwarded-host':'public.example.invalid'}])await assert.rejects(h.authorize(new Request('http://localhost/admin',{headers}),true,local),denied);await assert.rejects(h.authorize(new Request('http://public.example/admin'),true,local),denied);await assert.rejects(h.authorize(new Request('http://localhost/admin'),false,local),denied);await assert.rejects(h.authorize(new Request('http://localhost/admin'),true,{DB:db}),e=>e.status===503);});
test('trusted JWKS rotation refresh and unavailable keys fail closed',async()=>{const h=harness();await h.authorize(request(await token()),false,env);h.rotate();await h.authorize(request(await token({},1)),false,env);assert.equal(h.requests.length,2);assert.ok(h.requests.every(url=>url===issuer+'/cdn-cgi/access/certs'));const offline=harness();offline.offline();await assert.rejects(offline.authorize(request(await token()),false,env),denied);});
test('public tools stay public and official links only enter protected workspace',()=>{assert.equal(legacyOfficialLocation(new URL('https://example.invalid/veto')),null);assert.equal(legacyOfficialLocation(new URL('https://example.invalid/map-randomizer?adminTournament=test&adminRound=quarter-final')),'/admin/tournaments/test/maps?round=quarter-final');assert.equal(legacyOfficialLocation(new URL('https://example.invalid/veto?adminTournament=test&adminMatch=sf-1')),'/admin/tournaments/test/maps?match=sf-1');assert.throws(()=>legacyOfficialLocation(new URL('https://example.invalid/veto?adminTournament=../escape&adminMatch=sf-1')));});
test('every concrete admin route guards independently; middleware guards assets and descendants',()=>{function walk(path){return fs.readdirSync(path,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path+'/'+e.name):[path+'/'+e.name]);}const files=walk('src/pages/admin').filter(p=>/\.(astro|ts)$/.test(p));assert.equal(files.length,15);for(const file of files){const source=fs.readFileSync(file,'utf8');assert.match(source,/await authorizeAdmin\(/,file);assert.doesNotMatch(source,/requireLocalAdmin\(/,file);}const middleware=fs.readFileSync('src/middleware.ts','utf8');assert.match(middleware,/authorizeAdmin/);assert.match(middleware,/isAdminPath/);});
test('all page and asset paths enforce online reads/writes before form/body work',async()=>{const h=harness(),jwt=await token();const paths=['/admin','/admin/teams','/admin/players','/admin/maps','/admin/brackets','/admin/matches','/admin/tournaments','/admin/tournaments/new','/admin/tournaments/test','/admin/tournaments/test/setup','/admin/tournaments/test/participants','/admin/tournaments/test/roster','/admin/tournaments/test/bracket','/admin/tournaments/test/maps','/admin/tournaments/test/matches','/admin/tournaments/test/matches/m1',...['teams','players','maps','tournaments'].map(c=>'/admin/assets/'+c+'/test')];for(const path of paths){const req=(method,t)=>new Request('https://'+hostname+path,{method,headers:t?{'Cf-Access-Jwt-Assertion':t}:{}});for(const method of ['GET','HEAD','POST'])await assert.rejects(h.authorize(req(method),false,env),denied);for(const method of ['GET','HEAD'])assert.equal((await h.authorize(req(method,jwt),false,{...env,ADMIN_WRITES_ENABLED:'false'})).writes,false);await assert.rejects(h.authorize(req('POST',jwt),false,{...env,ADMIN_WRITES_ENABLED:'false'}),denied);assert.equal((await h.authorize(req('POST',jwt),false,env)).writes,true);}});
