import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {testAdminDatabase,testActor} from './helpers/admin-database.mjs';
import {mutationDatabase,auditActions} from '../src/admin/audit.mjs';
import {createTournament,deleteTestTournament} from '../src/admin/tournaments.mjs';
import {saveAsset} from '../src/admin/assets.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const name of fs.readdirSync('migrations').sort())sql.exec(fs.readFileSync('migrations/'+name,'utf8'));sql.exec("INSERT INTO teams(id,name,tag,region)VALUES('team','Original','T','ID')");const raw={};const db=testAdminDatabase(raw,sql);return{sql,raw,db,events:()=>sql.prepare('SELECT * FROM admin_audit_log').all()};}
test('one successful persisted mutation records actor, controlled action/entity and server timestamp',async()=>{const f=fixture();await mutationDatabase(f.db,'EDIT_TEAM','team').prepare('UPDATE teams SET name=? WHERE id=?').bind('Edited','team').run();const [event]=f.events();assert.equal(f.events().length,1);assert.equal(event.actor_sub,testActor.sub);assert.equal(event.actor_email,testActor.email);assert.equal(event.action,'EDIT_TEAM');assert.equal(event.entity_type,'team');assert.equal(event.entity_id,'team');assert.match(event.id,/^[a-f0-9-]{36}$/);assert.match(event.created_at,/^\d{4}-\d{2}-\d{2}T/);assert.deepEqual(Object.keys(event).sort(),['id','actor_sub','actor_email','action','entity_type','entity_id','created_at'].sort());});
test('validation, stale updates, SQL failure and untrusted/read-only context produce no success event',async()=>{const f=fixture();await assert.rejects(createTournament(f.db,{name:''}));const result=await mutationDatabase(f.db,'EDIT_TEAM','team').prepare("UPDATE teams SET name='stale' WHERE id='missing'").run();assert.equal(result.meta.changes,0);await assert.rejects(mutationDatabase(f.db,'EDIT_TEAM','team').prepare('UPDATE teams SET name=NULL').run());assert.throws(()=>mutationDatabase(f.raw,'EDIT_TEAM','team'),e=>e.status===403);const readOnly=testAdminDatabase({},f.sql,testActor,false);assert.throws(()=>mutationDatabase(readOnly,'EDIT_TEAM','team'),e=>e.status===403);assert.throws(()=>mutationDatabase(f.db,'client-invented','team'));await assert.rejects(mutationDatabase(f.db,'EDIT_TEAM','team').batch([f.raw.prepare("UPDATE teams SET name='bypass'")]),e=>e.status===403);assert.equal(f.events().length,0);assert.equal(f.sql.prepare('SELECT name FROM teams').get().name,'Original');});
test('audit persistence failure rolls back domain mutation and entire multi-statement batch',async()=>{const f=fixture();f.sql.exec("CREATE TRIGGER reject_audit BEFORE INSERT ON admin_audit_log BEGIN SELECT RAISE(ABORT,'audit unavailable');END");const scoped=mutationDatabase(f.db,'EDIT_TEAM','team');await assert.rejects(scoped.batch([scoped.prepare("UPDATE teams SET name='Edited' WHERE id='team'"),scoped.prepare("UPDATE teams SET tag='X' WHERE id='team'")]));assert.deepEqual({...f.sql.prepare('SELECT name,tag FROM teams').get()},{name:'Original',tag:'T'});assert.equal(f.events().length,0);});
test('TEST tournament deletion retains creation/deletion audit with no FK',async()=>{const f=fixture();const id=await createTournament(f.db,{name:'Audit Test',start_date:'2026-10-01',end_date:'2026-10-02',is_test:'1'});await deleteTestTournament(f.db,id,{confirmed:'yes',confirm_name:'Audit Test'});assert.equal(f.sql.prepare('SELECT count(*) n FROM tournaments').get().n,0);assert.deepEqual(f.events().map(e=>[e.action,e.entity_id]),[['CREATE_TOURNAMENT',id],['DELETE_TEST_TOURNAMENT',id]]);assert.equal(f.sql.prepare('PRAGMA foreign_key_list(admin_audit_log)').all().length,0);});
test('inline team/player creation events accompany parent event in same transaction',async()=>{const f=fixture(),db=mutationDatabase(f.db,'SAVE_ROSTER','test');await db.batch([db.prepare("UPDATE teams SET tag='S' WHERE id='team'"),db.prepare('INSERT INTO players(id,uid,current_ign,name)VALUES(?,?,?,?)').bind('inline-player','123','Fixture','Fixture')]);assert.deepEqual(f.events().map(e=>[e.action,e.entity_id]),[['SAVE_ROSTER','test'],['CREATE_PLAYER','inline-player']]);});
test('all controlled actions match schema allowlist and cannot log arbitrary metadata',async()=>{const f=fixture();for(const action of Object.keys(auditActions))await mutationDatabase(f.db,action,'fixture-id').prepare("UPDATE teams SET tag='T' WHERE id='team'").run();assert.equal(f.events().length,Object.keys(auditActions).length);assert.ok(f.events().every(e=>e.actor_email===testActor.email));});
test('asset revert and audit are atomic; failed audit keeps old reference',async()=>{const f=fixture(),key='teams/team/logo/'+ 'a'.repeat(64)+'.webp';f.sql.prepare('UPDATE teams SET logo_asset_key=?').run(key);f.sql.exec("CREATE TRIGGER reject_audit BEFORE INSERT ON admin_audit_log BEGIN SELECT RAISE(ABORT,'audit unavailable');END");await assert.rejects(saveAsset(f.db,null,'teams','team',{intent:'revert',expected:key}));assert.equal(f.sql.prepare('SELECT logo_asset_key FROM teams').get().logo_asset_key,key);assert.equal(f.events().length,0);f.sql.exec('DROP TRIGGER reject_audit');await saveAsset(f.db,null,'teams','team',{intent:'revert',expected:key});assert.equal(f.sql.prepare('SELECT logo_asset_key FROM teams').get().logo_asset_key,null);assert.equal(f.events()[0].action,'REVERT_ASSET');});
