CREATE TABLE admin_audit_log (
 id TEXT PRIMARY KEY NOT NULL,
 actor_sub TEXT NOT NULL CHECK(length(actor_sub) BETWEEN 1 AND 256),
 actor_email TEXT NOT NULL CHECK(length(actor_email) BETWEEN 3 AND 254),
 action TEXT NOT NULL CHECK(action IN ('CREATE_TEAM','EDIT_TEAM','CREATE_PLAYER','EDIT_PLAYER','CREATE_MAP','EDIT_MAP','CREATE_TOURNAMENT','EDIT_TOURNAMENT','SAVE_SETUP','COMPLETE_TOURNAMENT','DELETE_TEST_TOURNAMENT','SAVE_PARTICIPANTS','SAVE_ROSTER','MOVE_ROSTER_PLAYER','CONFIRM_BRACKET','CONFIRM_MAPS','SAVE_RESULT','FULL_WALKOVER','CORRECT_RESULT','SAVE_DETAILS_DRAFT','COMPLETE_DETAILS','CORRECT_DETAILS','PARTIAL_WALKOVER','UPLOAD_ASSET','REPLACE_ASSET','REVERT_ASSET')),
 entity_type TEXT NOT NULL CHECK(entity_type IN ('team','player','map','tournament','match','asset')),
 entity_id TEXT NOT NULL CHECK(length(entity_id) BETWEEN 1 AND 256),
 created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX admin_audit_log_created ON admin_audit_log(created_at,id);
