/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.uat.jsonc --include-runtime=false --env-interface=R2UATBindings src/data-access/r2-bindings.d.ts` (hash: 6e4cd042a261c1f98bf0717936597dca)
interface __BaseEnv_R2UATBindings {
	CFL_ASSETS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../dist/server/entry");
	}
	interface Env extends __BaseEnv_R2UATBindings {}
}
interface R2UATBindings extends __BaseEnv_R2UATBindings {}
